dist: trusty
group: beta
language: ruby
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - 2.4.0
  - rbx-3
  - jruby-9.0.5.0
  - jruby-9.1.2.0
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
  fast_finish: true
script: bundle exec rspec spec
notifications:
  email:
    - semmons99@gmail.com
    - andreas@aloop.org
    - weppos@weppos.net
